### ISSUE TITLE
Example of Neotypes with Zio?

### ISSUE THREAD

**Issue by PhilAndrew** [neotypes/neotypes#106]
Hi I'm really looking for an example of this with Zio

**Comment by BalmungSan** [comment]
Hi @PhilAndrew are the examples in the documentation enough?

+ [ZIO Task](https://neotypes.github.io/neotypes/alternative_effects.html)
+ [ZIO ZStream](https://neotypes.github.io/neotypes/streams.html)

Or is there something else that you consider is missing?

**Comment by PhilAndrew** [comment]
Thanks, I guess I didn't look very hard, it works now with ZIO.
