### ISSUE TITLE
Parameterized queries not consistent

### ISSUE THREAD

**Issue by Chrisss93** [neotypes/neotypes#11]
This may be an upstream issue, but I'm wondering why the DeferredQueryBuilder only correctly interpolates queries where  parameters are in the node properties of the cypher query. Whereas if we want to parameterize say the node label or the node property name, we need to instead use DeferredQueryBuilder's `+` operator.

**Comment by dimafeng** [comment]
Hi @Chrisss93,
Thank you for being an early adopter. You're right, it's an upstream issue (feature).
The following code
```scala
val label = "USER"
c"match (a:$label) return a"
```
.. is an equivalent of:
```java
tx.run( "match (a:$label) return a", parameters( "label", message ) );
```
in Java Driver and not valid.

As you said, a valid way to do it would be:
```scala
val name = "John"
val label = "USER"
c"create (a:" + label + c" {name: $name})"
```

**Comment by Chrisss93** [comment]
Understood - probably obvious for people with more neo4j knowledge. Luckily it's at least in the docs. Keep up the good work!
