### ISSUE TITLE
Add a derive mapper method

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#121]
As a best practice to reduce compile times, it is better to use semi-automatic derivation instead of the full automatic one.
This allows us to cache important instances, especially for recursive or nested data structures.

For example, I usually do this with **Circe**:

```scala
final case class Foo(data: String)
final case class Bar(id: Int, foo: Foo)
final case class Baz(flag: Boolean, bar: Bar)

private implicit final val fooEncoder: Encoder[Foo] = deriveEncoder
private implicit final val fooEncoder: Encoder[Bar] = deriveEncoder
private implicit final val fooEncoder: Encoder[Baz] = deriveEncoder
```

I would like to do the same with **neotypes** `Mappers`.
But, currently, we do not provide any way to do this.

**Comment by geoffjohn11** [comment]
I'll take a crack at this one

**Comment by BalmungSan** [comment]
Duplicate of #197
