### ISSUE TITLE
Question: Why streaming queries always rollback?

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#15]
Hi,

Not sure if I am missing something, but it seems to me that when you stream a query, at the end, you always rollback the query.

```scala
F.success(sb.onComplete(stream(t)) {
  t.rollback()
})
```
-- taken from [here](https://github.com/neotypes/neotypes/blob/master/core/src/main/scala/neotypes/DeferredQuery.scala#L25).

Is there any reason for this?
Or am I missing something?

------

BTW, Other question.
It seems that, streaming is only valid when requesting data. It is possible to _insert_ data coming from an Stream?

To be honest, I am new to Neo4j too, so I don't know if that does even make sense.
Maybe, the best way to do that, would be to use the same `transaction` to each `create` and `execute` them on my **Stream**?

**Comment by dimafeng** [comment]
Hi @BalmungSan,

The rationale behind is that, I'm not sure if steaming is applicable to operations with mutations (as you mentioned in your message as well).  If it's needed, it's possible to manage transaction manually. But since I don't know all use cases, I'm open to suggestions 😁 

Do you envision such a need to mutate the data and stream the result in your application?

**Comment by BalmungSan** [comment]
Hi @dimafeng,

Effectively, after a cup of coffee, I realized that _"inserting"_ a **Stream** does not make sense, rather I should insert independently every element of the **Stream**, that way, if one fails, the others no - which, kinda makes sense for a streaming semantics.

Given that, I agree with the `stream` method working only on queries _(`MATCH` statements)_.
However, I am not sure yet, if that `rollback` is really necessary at all.

As I said, I am new to Neo4j too, so I may be mistaken. But, giving a look to the documentation of the java driver, I only see transactions being used for mutations / insertions, not for queries.
I understand that, probably. the session uses a managed transaction under the hood, but do they `rollback` each select?

**Comment by BalmungSan** [comment]
After #164 this is no longer true, **Streaming** operations are rollbacked in case of error otherwise committed.
