### ISSUE TITLE
Making schema evolution safer

### ISSUE THREAD

**Issue by fredshonorio** [neotypes/neotypes#20]
Do you have any plans or ideas to make queries more amenable to schema changes? Specifically, one thing that bothers me is writing labels and property names in the query, which makes evolving the schema very hard.
I've made two attempts at this, for example:
https://github.com/fredshonorio/neu/blob/master/src/test/java/com/fredhonorio/neu/query/VarTest.java
and
https://github.com/fredshonorio/nod/blob/master/src/main/scala/nod/QueryExample.scala

and I'm not particularly satisfied with any of them.

**Comment by dimafeng** [comment]
Hi @fredshonorio,

It's good idea to make queries more type safe but I haven't thought about it yet.
Two things come to my mind:
1) Neo objects are schemaless so it's challenging to force schema in the queries
2) Cypher seems to be more complex in syntax comparing to SQL so creating a type DSL that covers all features might be complex.

Please let me know if you have progress with it.
