### ISSUE TITLE
Provide support for decoding ADTs from Nodes / Relationships

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#235]
Since we already support decoding key-value structures like `Node` or `Relationship` into **case classes**, it may make sense to allow decoding into an **ADT** where _(following what other libraries, e.g. **circe**, do)_ we read a property `type` to determine which **case class** to create.

Related #234 & #201

**Comment by PerWiklander** [comment]
Wouldn't it be natural to get the `type` information from a label on the Node or the type of the relationship, instead of introducing an extra property?

**Comment by BalmungSan** [comment]
@PerWiklander ´The new explicit codecs supports multiple ways to decode a `Node` / `Relationship` into an **ADT**, including a `type` field and the `label` :)
