### ISSUE TITLE
Add more streaming tests

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#240]
This issue is built on #221

For now, we provide a basic set of tests for our **Stream** abstraction and implementations.
While those are enough to guarantee the correct behaviour of the implementation of simple usage, they leave a lot of things open, which would be good to test.

For example, it would be good to add:
_(in order of importance)_

+ **ConcurrentStreamingDriverSpec.**: For ensuring the correct behaviour of concurrent queries using a `StreamingDriver`; similar to **ConcurrentDriverSpec.**.
+ **StreamResourceSpec**: For ensuring the correct behaviour of the `resource` method; similar to **AsyncGuaranteeSpec**.
+ **StreamingQueryExecutionSpec**: As an extension to **QueryExecutionSpec** for also validating the `stream` execution method _(it would be even better if this one could also run all the test on **QueryExecutionSpec** but using a `StreamingDriver` instead)_.
+ **StreamingDriverSpec**: As a showcase of many basic queries using a `StreamingDriver`; similar to **DriverSpec** _(it would be even better if those two could inherit from a single trait that provides all the tests)_.

**Comment by geoffjohn11** [comment]
I can try to work on these

**Comment by geoffjohn11** [comment]
@BalmungSan 
For the ConcurrentStreamingTest it looks like a new method will need to be added to the the StreamTestKit behavior to support the test, somethig like this:

```
trait Behaviour {
   def streamToFList[A](stream: S[A]): F[List[A]]
   def streamInstance: Stream.Aux[S, F]
   def streamConcurrently(stream1: S[Unit], stream2: S[Unit]): S[Unit]
 }
```

 The implementation for Fs2 looks pretty straightforward, something like this:

 ```
 override def streamConcurrently(stream1: Fs2IoStream[Unit], stream2: Fs2IoStream[Unit]): Fs2IoStream[Unit] = stream1.concurrently(stream2)
```

Is this the general idea for the concurrent test

**Comment by BalmungSan** [comment]
Hi @geoffjohn11 thanks for looking into this and sorry for taking too long to answer!

>  def streamConcurrently(stream1: S[Unit], stream2: S[Unit]): S[Unit]

Yeah, that should work.

> Is this the general idea for the concurrent test?

Yes, we should ensure that running two queries _"at the same time"_ is supported.
