### ISSUE TITLE
Feature: case class mapper for maps

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#26]
If using [`map projections`](https://neo4j.com/docs/cypher-manual/current/syntax/maps/#cypher-map-projection), **neotypes** is unable to map the returned values to case classes. A common use case I have _(which I believe could be useful for others)_ is having a node with a lot of fields to which you want to add some other computed fields and return that as a case class.
Example:

```scala
c"""MATCH (u: User { name: $name })
      ...
     RETURN u { .*, score: sum(???) }
    ORDER BY u.score
    LIMIT 10""".query[ScoredUser].list(session)
```

Right now we are solving the problem like this:

```scala
c"""MATCH (u: User { name: $name })
      ...
     RETURN
       u.name AS name,
       ...
       sum(???) AS score
    ORDER BY u.score
    LIMIT 10""".query[ScoredUser].list(session)
```

Not a big deal, but is kind of tedious to add every property to the return.

------

**Disclaimer:** I do not know anything about shapeless, so I can not help with this. Being honest, I do not even know if this is easy, doable, difficult or impossible lol 😅 
But I guess I do not lose anything opening this just to see if anyone knows how to do it.

**Comment by dimafeng** [comment]
@BalmungSan good finding 😁 I haven't used `map projections` before but I'll play with it to get a clearer picture.
