### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#27]
So, I was reading about licenses today _(mainly because I am thinking in starting an open source project)_, and I was surprised both to notice that _this_ does not have any, and that means [nobody can use it _(legally speaking)_](https://choosealicense.com/no-permission/). :anguished:

I strongly believe that is not what you wanted. Thus, I hope this just works as a reminder. 😄 

------

# Edit

I just noticed that in the `build.sbt` you specify this is under the MIT License.  :+1:
Anyways, I still believe, it would be good to specify that on the `README` and / or adding the `LICENSE` file to the root of this repo.

**Comment by dimafeng** [comment]
@BalmungSan good point! I'll fix it.

**Comment by dimafeng** [comment]
Fixed 😁
