### ISSUE TITLE
Wrap UUID parsing exceptions into Neotypes exceptions

### ISSUE THREAD

**Issue by markarasev** [neotypes/neotypes#343]
UUIDs are mapped using this ValueMapper:

https://github.com/neotypes/neotypes/blob/3a2edd01ff5ff13cfb2c0c9c61a4745f72b43738/core/src/main/scala/neotypes/mappers.scala#L535-L536

But `UUID.fromString` throws `IllegalArgumentException`s, `NumberFormatException`s and probably other types of exceptions which are not instances of `NeotypesException`. Ultimately, these exceptions will be returned by the library and I think it would be nicer if they were included in the `NeotypesException` hierarchy in order to allow the user to implement reliable logic when these errors appear.

**Comment by markarasev** [comment]
Wow, that was quick. Thanks!

**Comment by BalmungSan** [comment]
@markarasev you are welcome!
We still need to do a new release in order to ship the fix, I guess once #344 is merged we could do one :)
