### ISSUE TITLE
Add scaladoc

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#49]
It would be good to also have the scaladoc of the library published together with the documentation.

This also implies that we should add all the scaladoc comments that are missing right now.

**Comment by SumLare** [comment]
Hey! I'm learning scala and would love to help where I can, do you have any suggestions on how to approach this issue?

**Comment by BalmungSan** [comment]
Hi @SumLare welcome to the project _(and the community)_ in general. Hope you are enjoying your learning.

The first step would be to generate the scaladoc locally on your machine using **SBT**. If everything works, it should generate some html + css +js files that when you open them on a browser, you should see something like [this](https://www.scala-lang.org/api/current/).
It will be somewhat empty, since we do not have too much documentation, but the `mappers` object should have some.

The second step would be to add more documentation, the project is somewhat small, and _(I hope)_ most of the methods should be simple enough, that understanding and documenting them should be straightforward.
Do not worry too much if you do not understand some of them, since we are using effects and other FP topics, you may learn about those in the process.

Then you can open a PR with the changes, you may add comments on places where you have doubts, I will try to answer ASAP.

The final step would be to modify the **travis** file to include the generation of the `scaladoc` and upload it to github pages.
@dimafeng is the one that knows about that part.

**Comment by SumLare** [comment]
Thanks a lot! I'll look into it!

**Comment by geoffjohn11** [comment]
I made an initial attempt at adding doc here
https://github.com/neotypes/neotypes/pull/55/commits/eef633de12080175bee4a2ea82bf5723febd6c44

**Comment by BalmungSan** [comment]
#82 adds the scaladoc to the microsite.

Now we just need to finish documenting everything!
But, that is an ongoing effort _(that probably will never finish)_, so I will be closing this issue.
