### ISSUE TITLE
Request: ZIO 2.x support

### ISSUE THREAD

**Issue by PhilAndrew** [neotypes/neotypes#522]
ZIO 2.x is going along https://zio.dev/next/howto/migrate/zio-2.x-migration-guide/

Request to support

**Comment by BalmungSan** [comment]
Hi @PhilAndrew just like how we did for the **cats-effect** `3.x` release, we won't upgrade until the `2.x` is officially released _(since we can't provide both versions)_.
Also, a quick look at the migration guide suggests that we either could not upgrade or that our library won't be idiomatic for **ZIO** users _(if ever it was)_.

In any case, if you or anyone wants to open a PR to do the migration we are more than happy to review it and merge it when the time comes.

**Comment by masonedmison** [comment]
@BalmungSan I am just curious about your take on what is different about v2.X that would make it any less idiomatic than v1.X? Is it the fact that `ZManaged` is no more? At any rate, I have been getting more familiar with ZIO for work and would be happy to try to add support for this once an official release is out for v2.  I _think_ the current release candidate version should be relatively stable so we might be able to get a headstart before it's officially released :)

**Comment by BalmungSan** [comment]
@masonedmison

> I am just curious about your take on what is different about v2.X that would make it any less idiomatic than v1.X? Is it the fact that ZManaged is no more? 

Mostly yes, it seems we would need to look into `ZLayers` madness or see how to trick the type system into using the `R` type. But, again, I really haven't looked into that.

> At any rate, I have been getting more familiar with ZIO for work and would be happy to try to add support for this once an official release is out for v2

That would be awesome!

>  I think the current release candidate version should be relatively stable so we might be able to get a headstart before it's officially released :)

Sure a WIP PR is more than welcome!

**Comment by masonedmison** [comment]
@BalmungSan Sounds good. Just started dinking around with it. As soon as I get something close-ish, I will open up a WIP PR :)

**Comment by BalmungSan** [comment]
Thanks to the work of @masonedmison this is technically closed.
So now all that remains is when to merge and release?

I am not a **ZIO** user myself so I really don't care.
Thus, I am asking to all **ZIO** users of **neotypes** to vote, should we release now (🚀) or when the official `2.0` release is done (👀)?

PS: Note that I don't plan to support both versions so releasing now means no more **ZIO** `1.0` releases.

**Comment by BalmungSan** [comment]
Closed by #524
