### ISSUE TITLE
Future considerations: Neo4j v5, Akka & Monix

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#561]
# Neo4j v5

The **Neo4j** **Java** driver just released its new `5.0.0` version which deprecates the `RxSession` in favor of the new `ReactiveSession` which is based on the `Flow` API introduced in **Java 9**.

This has many implications and forces us to take some difficult decisions.

## Drop Java 8

Since the `Flow` API is only available since **Java 9** AFAIK.

While I personally dropped **Java 8** from my own projects long ago and lately migrated all the projects I work on from **Java 11** to **Java 17**. I don't feel comfortable with forcing **neotypes** users to require at least **Java 9**.

Now, being rational, since that requirement is coming from the **Java** driver itself, it seems most users would be forced to do the upgrade nevertheless.

## How to interop

Now the **Java** driver will return a `Flow.Publisher` rather than an `org.reactivestreams.Publisher`, thus our current `Stream.fromPublisher` implementations won't work.

Based on a quick research, it seems none of the currently supported libraries provide an out-of-the-box integration with that API. Thus, AFAIK, we have three options.

1. Transform a `Flow.Publisher` into a `org.reactivestreams.Publisher` using this: https://www.reactive-streams.org/reactive-streams-1.0.3-javadoc/org/reactivestreams/FlowAdapters.html#toPublisher(java.util.concurrent.Flow.Publisher) and thus ensuring everything works as expected. The downside, more conversions happening under the hood and probably hurting performance.
2. Wait for those libraries to support `Flow.Publisher` before upgrading; we probably may help in that endeavor. But this would take a while and we don't know if those libraries would like to support that right now.
3. Re-implement such integrations from scratch on each module.

# Akka

On top of the previous discussion, we also have the whole **Akka** situation.
I personally think the best is to remove the **AkkaStreams** module from **neotypes** since I don't want to deal with legal bullshit in the future; originally my idea was to just pin to `the 2.6` series until we release a **Scala 3** compatible version and then remove it, that way I think we would have done our best effort for them.
Nevertheless, in light of the previous discussion maybe it would simplify our lives to just remove it now?

# Monix

In a similar vein as the previous topic, I personally have tried to keep dimafeng's original vision of making **neotypes**

> Not opinionated on side-effect implementation - you can use it with any effect system of your preference (Future, typelevel, ZIO, Monix) by implementing a simple typeclass.

As long as it doesn't cause much trouble.
To be honest, I personally just try to make it first-class support for **typelevel / cats-effect**, while others are best effort from my side; however, lately we have had many helpful contributors _(e.g. the whole **ZIO 2** PRs! 🎉)_

Now, if we decide that the best is to re-implement the `Flow -> Stream` logic on each module I would be tempted to also remove the **monix** module if such integration proves to be not trivial.

-----

Those are a lot of topics to unpack so I don't want to open a vocation pool now, but rather would prefer to know what you all think.

**Comment by BalmungSan** [comment]
@tjarvstrand 

> Java 9 is five years old at this point. I personally don't see any issue with dropping it.

:+1:

> Does the `toPublisher`-conversion happen only at stream creation or is there overhead for each element in the stream?

Technically speaking we call the method only during creation, but such conversion is probably creating a wrapper that redirects each `onNext` call and all that.
But, I also think is probably not a big deal anyways.

> but reading the text I don't see what the legal issue would be with maintaining support for it

If I understood everything correctly, if we update **Akka** to the `2.7` we have to change our license to be the same as theirs.
But, since I am not sure I understand it correctly I also prefer to just drop it since I don't want to have to deal with it and any other future license change.

**Comment by geoffjohn11** [comment]
1.  Drop Java 8
2. Interop with Flow.Publisher path of least resistance might not be the best way.  Not too sure about this one
3. Fix the akka version to 2.6 or drop it.  Looks like that's what Flink is doing https://flink.apache.org/news/2022/09/08/akka-license-change.html
4. Not sure about Monix support, perhaps see what it would take to keep it.

**Comment by BalmungSan** [comment]
Yeah, I think that for now, I will follow the oath of least resistance with `Flow` which implies we can keep **monix**.
