### ISSUE TITLE
API to allow returning records AND ResultSummary

### ISSUE THREAD

**Issue by hindog** [neotypes/neotypes#564]
Currently there's no way to issue a query for records while and accessing the ResultSummary from the same query

**Comment by BalmungSan** [comment]
Hi @hindog sorry for the delay.

I have been thinking about this, and found that a good solution would not be as simple as I originally thought. Thus, and in light that during this year I will refactor the mappers _(see #236 )_ I don't think it is worth it to make a full change now to make another latter.

Thus, I thought the best is to provide a simple workaround. The idea would be that you could do this:

```scala
c"SOME QUERY".query[(ResultSummary, List[Foo])].execute(d)
```

It should allow you to do what you want but it would be limited to:
+ The `execute` command.
+ To pairs where the `ResultSummary` has to be the first element and a `List[T]` the second.

We may make it a little bit more flexible like allowing both a single `Foo` and a `Option[Foo]` as the second argument.

Before opening the PR, I wanted to confirm with you if this would be good enough in the meantime.

**Comment by hindog** [comment]
@BalmungSan apologies for the delay on my end :)

I think I looked at doing something like that initially, but in our case we rely heavily on the streaming API (specifically ZIO's `ZStream`), which I don't think would be covered in this case, right?  From what I can tell, the contract for the `StreamingTransaction` would need to change:

```
sealed trait StreamingTransaction[S[_], F[_]] extends Transaction[F] {
  def stream[T](query: String, params: Map[String, QueryParam])
               (implicit resultMapper: ResultMapper[T]): S[T]
}
```

For this case, I wonder a user-provided callback would work?  Eg, something like this:

```
  def stream[T](query: String, params: Map[String, QueryParam], onConsume: ResultSummary => F[Unit])
               (implicit resultMapper: ResultMapper[T]): S[T]
```

(For what it's worth, we currently use an internally-developed Neo4j Scala API, so we aren't blocked by this, other than we were looking at swapping out for neotypes but this was preventing us from doing do.)

**Comment by BalmungSan** [comment]
@hindog as I said, I am currently in the process of re-designing and re-implementing the whole mappers logic, I will be commenting more on the matter soon.

So, I personally will refrain from making big changes to the project that have to be reverted recently.

BTW, note that this use case is already being considered by that new design.

**Comment by BalmungSan** [comment]
@hindog I am currently working on the explicit decoders refactor I mentioned the other day.
It is still WIP but that PR will also introduce a way to get the result summary and the records.

The idea is that the API will look like this:

```scala
"...".execute.void(driver) // F[Unit]
"...".execute.resultSummary(driver)  // F[ResultSummary]
"...".query(ResultMapper[T]).single(driver) // F[T]
"...".query(ResultMapper[T]).withResultSumary.single(driver) // F[(T, ResultSummary)]
"...".query(ResultMapper[T]).withResultSumary.list(driver) // F[(List[T], ResultSummary)]
"...".query(ResultMapper[T]).withResultSumary.stream(driver) // S[Either[T, ResultSummary]] - The last element of the stream will be the Right(rs)
```

WDYT?
