### ISSUE TITLE
Upgrade to Neo4j 4

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#58]
A new version fo the Neo4j Java driver has been released.

The [changelogs](https://github.com/neo4j/neo4j-java-driver/wiki/4.0-changelog) state that probably the most important change is the support of an **Rx** driver. It would be great if we can provide wrappers for those too for our **Streaming** implementations, for example since I use `http4s` I end up converting everything into an `fs2` **Stream**.

**Comment by PhilAndrew** [comment]
Can this current version connect to Neo4J 4? I tried and it failed to connect ...

**Comment by BalmungSan** [comment]
According to the [**Java** driver documentation](https://github.com/neo4j/neo4j-java-driver/wiki) this `1.7` version of the driver is not compatible with `4.0` servers. And since this is only a wrapper over that driver, then this one will neither connect.

I believe we can just bump the driver a do a new release without too much problem since it seems there weren't any sourcecode incompatibilities, without doing all that we wanted to do.

I hope to get that done before the end of this week.
