### ISSUE TITLE
Should ResultMapper derivation support nested case classes? 

### ISSUE THREAD

**Issue by i10416** [neotypes/neotypes#671]
https://github.com/neotypes/neotypes/blob/672a3317dd33debad71a0d9b5b2fe8441896b176/tests/src/test/scala/neotypes/generic/DeriveCaseClassProductMapSpec.scala#L67

It seems Neo4j does not support nested properties.

https://github.com/neo4j/neo4j/issues/6349
https://github.com/neo4j/neo4j/issues/6282

**Comment by BalmungSan** [comment]
Yes, the properties of a `Node` / `Relationship` can not be other complex objects _(with a couple of exceptions)_.
However, you can _(AFAIK, please correct me if wrong)_ return an arbitrary nested `Maps` and `Lists` :)
Which is what we use in that example.

**Comment by i10416** [comment]
Ah, I understood. Thanks for clarification.
