### ISSUE TITLE
random thought: graphql integration

### ISSUE THREAD

**Issue by i10416** [neotypes/neotypes#672]
This is a low priority feature request. If it sounds nonsense , feel free to close.

There is a thin Java library for integration between neo4j and graphql. https://github.com/neo4j-graphql/neo4j-graphql-java

It would be nice if there is a Scala one which works well with Grackle or Caliban.

**Comment by BalmungSan** [comment]
This sounds interesting, although I wonder if we actually need to do something.
I speak out of ignorance, but couldn't users just use that **Java** library directly to transform the **GraphQL** request into a **Cypher** query and then just pass that query into **neotypes**?

**Comment by i10416** [comment]
> I speak out of ignorance, but couldn't users just use that Java library directly to transform the GraphQL request into a Cypher query and then just pass that query into neotypes?

Yeah, I suspect in the same way and I wanted to hear from someone what they think.

Just combining graphql and neotypes will work fine with a bit awkwardness.

**Comment by BalmungSan** [comment]
@i10416 if you want, this may be a good spec :)
Just like the `AlgorithmSpec` where we actually don't test the functionality of **neotypes**, but rather just show how it can interact with other parts of the ecosystem.
