### ISSUE TITLE
question: should we sparate integration tests from unit tests?

### ISSUE THREAD

**Issue by i10416** [neotypes/neotypes#674]
While working on Scala 3 support, I found tests module contains both unit tests and integration tests.

When it comes to synchronous modules, which are less likely effectful, it feels convenient if I could run unit tests independently as I did in #666  (`++3.3.0 core/compile`）. This will not requre developpers to select tests from whole tests by sbt's testOnly task.

**Comment by BalmungSan** [comment]
Actually, I would rather move all the tests into a single `test` module that depends on all other modules, this would simplify the **sbt** configuration a lot.
Then, inside that single module, we could have three packages:

+ `neotypes.test.base`: For helpers.
+ `neotypes.test.unit`: For tests that don't require a living **Neo4j** database.
+ `neotypes.test.it`: For tests that do require a living **Neo4j** database.

That way, using the `testOnly` would be simpler.

**Comment by i10416** [comment]
Thanks.
After supporting most of modules, I don't think I need such a granularity for most of the time.
