### ISSUE TITLE
ResultMapper.tuple fails with complex types

### ISSUE THREAD

**Issue by turb** [neotypes/neotypes#806]
This fails:

```scala
  it should "derive a tuple composed of more complex types" in {
    val mapper = ResultMapper.tuple[Option[Int], Either[String, Boolean], List[Int], Map[String, String], Option[Set[Long]]]

    val input = NeoMap(
      properties = Map(
        "opt" -> Value.Integer(5),
        "either" -> Value.Bool(true),
        "list" -> Value.ListValue(List(Value.Integer(0), Value.Integer(10))),
        "map" -> NeoMap(Map("foo" -> Value.Str("bar"), "baz" -> Value.Str("quax"))),
        "none" -> Value.NullValue // it does not fail without this last one
      )
    )
    val result = mapper.decode(input)

    result.value shouldBe (Some(5), Right(true), List(0, 10), Map("foo" -> "bar", "baz" -> "quax"), None)
  }
```

All elements of the tuple are mixed up, because calling `values` to iterate over them calls `properties.valuesIterator.toList`, `properties` being a `Map` that does not keep entries order.

The easiest (but maybe not the right one?) way to fix this is to use a `SeqMap` for `NeoMap.properties` to keep the order of values in the Map, or introduce a distinct:

```scala
/** Represents a Neo4j heterogeneous ordered tuple */
final case class Tuple(properties: SeqMap[String, NeoType]) extends NeoObject
```

**Comment by BalmungSan** [comment]
**Neo4j** docs seem to suggest they are also unordered: https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#constructed-types
> The MAP data type is a heterogeneous, unordered collection of (Key, Value) pairs, where Key is a literal and Value can have any property, structural, or constructed type.

**Comment by BalmungSan** [comment]
The **Java** driver also seems to suggest they are unordered: https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/types/MapAccessor.html
> Access the keys, properties and values of an underlying unordered map by key
> Returns: all values in unspecified order

**Comment by turb** [comment]
> Do you know if Neo4j or the Java driver ensures some form of order? 
What I know is when keeping the given order, it works again.

If the order cannot be guaranteed, I think it's impossible to offer a tuple mapping, since as soon as you have twice the same type, it's impossible to know which one goes where. As the test case illustrates.

We are currently using 0.23 and tuples work fine even in those cases. That's when I tried to migrate to 1.1 that everything started to break, because it randomly tries to map apples into oranges.

**Comment by BalmungSan** [comment]
> If the order cannot be guaranteed, I think it's impossible to offer a tuple mapping, since as soon as you have twice the same type.

Well, a couple of things, to note:
1. There are other tuple mappers provided by the library, like the named one. And, you could even provide your own that does a `sorted`.
2. Originally, I also wondered if the unnamed one should accept `NeoMaps` or fail immediately. I thought it was better to allow it to work with `NeoMaps` even if the order couldn't be guaranteed just for flexibility. But, I can easily be convinced of changing that behavior.
3. Duplicate types don't matter that much here, the problem is not with two `Options` is just with having enough elements so the underlying `Map` becomes a `HashMap`.

> We are currently using 0.23 and tuples work fine even in those cases.
This intrigues me, can you tell me how does it work? Is the query using a map-projection by chance? Maybe those do preserve order?

**Comment by turb** [comment]
> Duplicate types don't matter that much here, the problem is not with two Options is just with having enough elements so the underlying Map becomes a HashMap.

You are perfectly right, I wondered with it worked with a tuple of 4, and not anymore with 5, and did not realize the switch to HashMap thing!

> This intrigues me, can you tell me how does it work? Is the query using a map-projection by chance? Maybe those do preserve order?

No map projection.

One example we have is:

```scala
c"""
      MATCH (e1:Entity1) WHERE e1.#$idProperty=${id.strValue}
      OPTIONAL MATCH (e1)<-[link:Rel1]-(e2:Entity2)
      OPTIONAL MATCH (e2)-[:Rel2]->(e3:Entity3)
      RETURN e1, link.property1, link.property2, e2, e2
    """
    .query(
        ResultMapper.tuple[
          Entity1,
          Option[Property1AnyVal],
          Option[Property2AnyVal],
          Option[Entity2],
          Option[Entity3],
        ],
      ).set(driver)
```

With 0.23 it was like this:

```scala
 sameQuery.query[
        (
          Entity1,
          Option[Property1AnyVal],
          Option[Property2AnyVal],
          Option[Entity2],
          Option[Entity3],
        ),
      ]
      .set(driver)

```

**Comment by BalmungSan** [comment]
Uhm that should work well, so yeah we need to fix this.
If you are motivated enough, it would be useful to have a simple test case that reproduces the issue and then confirm that using a `VectorMap` does fix the problem.

**Comment by turb** [comment]
You mean an integration test, broader than the one I posted above? I'll try to write something.

**Comment by BalmungSan** [comment]
Yeah it would be good to have both.
The one above could be added to the `ResultMapperSpec` and then a full integration test could go in the `DriverSpec`

**Comment by turb** [comment]
Created PR #808
